Support Windows/macOS
EnzymeAD/rust pull request #73
Opened 2024-02-07 06:06 UTC by motabbara

For this to work I also had to modify Enzyme CMakeLists.txt

Not sure whether these make sense so I guess this is more of a draft PR

[CMakeLists.txt](https://github.com/EnzymeAD/rust/files/14189702/CMakeLists.txt)

2024-02-07 06:46 UTC, ZuseZ4 commented
Thanks a lot! I looked through your CMakeList.txt changes and created this patch, can you make a PR for Enzyme core out of it? (I didn't had your email gh, so I couldn't commit in your name)
[patch.diff.txt](https://github.com/EnzymeAD/rust/files/14190017/patch.diff.txt)

Once that is merged I'll update the Enzyme submodule and merge this pr here.

2024-02-07 21:24 UTC, ZuseZ4 commented
Also @motabbara, if you are currently free, we are discussing that in our weekly open Enzyme call at https://mit.zoom.us/j/96000853439

2024-02-07 22:36 UTC, jedbrown reviewed
Are the Cargo.lock changes important/significant?

@ZuseZ4 Do you want to merge this into `macro2` instead?

2024-02-08 02:55 UTC, motabbara commented
> Are the Cargo.lock changes important/significant?
> 
> 
> 
> @ZuseZ4 Do you want to merge this into `macro2` instead?

I'll put it into macro2 and remove the lock file noise.

2024-02-08 03:25 UTC, motabbara commented
> Thanks a lot! I looked through your CMakeList.txt changes and created this patch, can you make a PR for Enzyme core out of it? (I didn't had your gh email, so I couldn't commit in your name) [patch.diff.txt](https://github.com/EnzymeAD/rust/files/14190017/patch.diff.txt) Once that is merged I'll update the Enzyme submodule and merge this pr here.
> 
> Also, do you know what happened to your cargo.lock? It is ~7 times the original size, did you maybe run x or x.py from that folder? I am not sure why it would otherwise change so much.
> 
> Final question, on which systems could you test this? We hope to add CI soonish, but I didn't got to it yet, so only some Linux versions are really tested. Something like this should print it: `rustc -Z unstable-options --print target-spec-json | grep llvm-target`

"llvm-target": "arm64-apple-macosx11.0.0",

2024-02-09 04:57 UTC, ZuseZ4 commented
@motabbara, I went ahead and created a similar PR to Enzyme, since I just tried to rebuild rust-enzyme and ended up with similar errors. I additionally to your patch also had to update the BCLoader CMakeLists, and I didn't needed your Mac specific changes, so I left these for you.

2024-02-09 05:06 UTC, ZuseZ4 requested changes

2024-02-09 05:06 UTC, ZuseZ4 commented on src/bootstrap/src/core/build_steps/compile.rs
> +                _ => ("", "so")
for linux it would also be lib as prefix, as with the dst_lib.
Also, I assume you will also need to update dst_lib with the prefix?

2025-03-26 06:25 UTC, ZuseZ4 commented
We have been supporting MacOs for a while now, so closing here.
Windows should also work to a limited degree, MSVC as the main compiler isn't supported, but that's to be fixed by Enzyme, not us.

2025-03-26 06:25 UTC, closed without merging